import type { Metadata } from "next";
import { Providers } from "../providers";
import "../../styels/globals.css"; // 🔥 Fixed typo: styles instead of styels
import Sidebar from "@/components/Userdashboard/Sidebar";
import UserNavbar from "@/components/navbars/UserNavbar";
import UserFooter from "@/components/Userdashboard/UserFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased font-poppins bg-[#04091d] text-white">
        <Providers>
          {/* Optional Top Nav */}
          {/* <MainNavbar /> */}
          <UserNavbar />

          <div className="flex min-h-screen">
            {/* Sidebar */}
            <Sidebar />

            {/* Main content */}
            <div className="flex flex-col flex-1">
              <main className="flex-1 p-6 overflow-auto">{children}</main>
              <UserFooter />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
