import type { Metadata } from "next";
import { Providers } from "../providers";
import "../../styels/globals.css";
import MainNavbar from "@/components/navbars/mainNavbar";
import MainFooter from "@/components/footer/MainFooter";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased  font-poppins bg-[#04091d]">
        <Providers>
          <div className="flex flex-col min-h-screen">
            <MainNavbar />

            <main className=" ">
              {children}

              <MainFooter />
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
