import type { Metadata } from "next";
import { Providers } from "../providers";
import "../../styels/globals.css";
import MainNavbar from "@/components/navbars/mainNavbar";
import MainFooter from "@/components/footer/MainFooter";
import { Poppins } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Add needed weights
  variable: "--font-poppins", // Define a CSS variable
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={poppins.variable}>
      <body className="antialiased  font-poppins bg-[#16142a]">
        <Providers>
          <div className="flex flex-col min-h-screen">
            <MainNavbar />

            <main className=" ">
              {children}

              <MainFooter />
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
