import type { Metadata } from "next";
import { Providers } from "../providers";
import "../../styels/globals.css";

export const metadata: Metadata = {
  title: "signup/login",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/Chat-GPT-Image-Apr-24-2025-02-07-44-PM-removebg-preview%20(2).webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased  font-poppins bg-[#04091d]">
        <Providers>
          <div className="flex flex-col min-h-screen">
            <main className=" ">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
