import type { Metadata } from "next";
import { Providers } from "../providers";
import "../../styels/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased  font-poppins bg-[#16142a]">
        <Providers>
          <div className="flex flex-col min-h-screen">
            <main className=" ">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
