import type { Metadata } from "next";
import { Providers } from "../providers";
import "../../styels/globals.css"; // 🔥 Fixed typo: styles instead of styels
import { Poppins } from "next/font/google";
import UserNavbar from "@/components/Userdashboard/UserNavbar";
import UserFooter from "@/components/Userdashboard/UserFooter";
import AdminSidebar from "@/components/Admindashboard/AdminSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={poppins.variable}>
      <body className="antialiased font-poppins ">
        <Providers>
          <SidebarProvider>
            <div className="w-full flex min-h-screen">
              {/* Sidebar */}
              <AdminSidebar />

              {/* Main content */}
              <div className="flex-1 flex flex-col   ">
                <UserNavbar />

                {/* Main content area */}
                <main className="flex-1">{children}</main>
                <UserFooter />
              </div>
            </div>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
